### ISSUE TITLE
highlight currently viewed area

### ISSUE THREAD

**Issue by sedrubal** [JohnMcLear/ep_table_of_contents#25]

**Comment by JohnMcLear** [comment]
Please explain what you want, unless you intend to put it in, in which case a PR would be welcome :)

**Comment by sedrubal** [comment]
Sorry :)

I'd find it great, if the currently viewed toc-point would be displayed highlighted.

I can't write `javascript` so I can't make a PR :smile: 

Maybe you can add a css rule like that:

```css
div#toc div#tocItems a.tocItem#tocItemCurrent{
	background: yellow;
	box-shadow:	0 0 50px yellow;
}
```

If you add the id `tocItemCurrent` to the currently viewed toc-point through javascript, everything is done ;)

Here you can see, what I mean:

![ep_snapshot](https://cloud.githubusercontent.com/assets/5571650/7620446/3afb6820-f9c0-11e4-9932-27316592cc15.png)
